### PR TITLE
add pypy7.2

### PR DESCRIPTION
**Pull request by mattip**
Add pypy 7.2 to the matrix

### CODE REVIEW

**Comment by antocuni** [comment]
updating `generate_jobs.py` is not enough, you also need to run it and manully update `.travis.yml`. Moreover, the readme says that we compile for the latest three versions, so I think it is fine to drop 6.0.

However, we need squeaky's portable build first: https://github.com/squeaky-pl/portable-pypy/issues/94

**Comment by mattip** [comment]
> However, we need squeaky's portable build first

Are you sure? I think these days we can rebuild the cffi modules in-place. How can I test that the build chain works?

**Comment by mattip** [comment]
Ahh, I see, I can reproduce the travis build and set the env variables appropriately.

We should also build NumPy like upstream does, downloading and linking to OpenBLAS

**Comment by antocuni** [comment]
well, currently the docker image installs squeaky's binaries, so they are definitely needed :)
https://github.com/antocuni/pypy-wheels/blob/master/docker/image/install_pypy.sh#L41

For ubuntu wheels, we could probably just use the official release, for if we want to build `manylinux2010` we definitely need to install portable pypys, else they won't run on the `manylinux2010` image

**Comment by antocuni** [comment]
> We should also build NumPy like upstream does, downloading and linking to OpenBLAS

I think we are already linking to openblas?

**Comment by mattip** [comment]
ahh, sorry, but then what is up with the scipy build failures in CI?

**Comment by antocuni** [comment]
> ahh, sorry, but then what is up with the scipy build failures in CI?
I don't know :(
Builds tend to break every once and then and I haven't looked at them for a while

**Comment by mattip** [comment]
reopen to restart travis

**Comment by mattip** [comment]
Hmm, it seems I need to break this into two prs, one to change the image and another to add the jobs to the ci matrix. 

“skipping docker push because this is a PR” make everything else fail.

**Comment by mattip** [comment]
Or maybe just merge this as-is and we can fix failures that crop up

**Comment by mattip** [comment]
Not clear why scipy build is failing - it cannot find lapack/blas?

**Comment by mattip** [comment]
The wheels that are successfully built do not appear on the index. Is it because this is a PR? The end of the numpy 7.2 python3.6 build says:
```
The command "python scripts/build_index.py wheelhouse/ubuntu/ /tmp/gh-pages/ubuntu" exited with 0.
0.01s$ ./scripts/commit-gh-pages.sh
Commit result...
travis/travis.rsa does not exists (probably because this is a PR)
exiting
The command "./scripts/commit-gh-pages.sh" exited with 0.
```

If so, could we get this merged and then fix the remaining problems once most of the wheels are uploaded?

**Comment by antocuni** [comment]
merged it, sorry for the delay :(

**Comment by mattip** [comment]
Thanks. How can I see what builds succeeded in the merge?

**Comment by antocuni** [comment]
This is the travis build corresponding to the merge: https://travis-ci.org/antocuni/pypy-wheels/builds/604471216
it seems that scipy jobs are failing in some `$PY/$PYPY` combinations, although I don't understand what is going on.
Looking at the logs, the jobs are failing when building numpy, but this should not happen because numpy is already built and thus should be installed by a wheel

**Comment by mattip** [comment]
I think the names collide. For instance is this wheel: numpy-1.17.1-pp370-pypy3_70-linux_x86_64.whl for python3.5 or 3.6?

**Comment by mattip** [comment]
I am not seeing the pypy3 72 wheels at all, for instance numpy-1.17.3-pp372-pypy3_72-linux_x86_64.whl does not exist https://antocuni.github.io/pypy-wheels/ubuntu/numpy/

**Comment by antocuni** [comment]
> for instance numpy-1.17.3-pp372-pypy3_72-linux_x86_64.whl does not exist https://antocuni.github.io/pypy-wheels/ubuntu/numpy/

Oh, I see the problem :(, it's basically a race-condition:
https://travis-ci.org/antocuni/pypy-wheels/jobs/604471224#L295

so, the job successfully built the numpy wheel, but failed to push to it `gh-pages` because some other job pushed to the repo in the meantime. It should probably work [next time the job run](https://travis-ci.org/antocuni/pypy-wheels/jobs/604471224)

**Pull request merged**
