### PR TITLE
Link against OpenBLAS

### PR DESCRIPTION
**Pull request by Juanlu001**
What do you think of this change? OpenBLAS is a maintained BLAS/LAPACK implementation that is widely used.

### CODE REVIEW

**Comment by antocuni** [comment]
When I do `pip install numpy` on linux, which one do I get? OpenBLAS or the standard blas/lapack?

Also, if we merge this, we need to update the README as well.

**Comment by Juanlu001** [comment]
I was precisely looking for that information, but could not find it... And the same goes for SciPy. Not sure how do they compile their wheels, perhaps @jaimefrio would like to chime in and shed some light?

**Comment by Juanlu001** [comment]
For reference: this is how the NumPy/SciPy/... wheels are generated https://github.com/MacPython/scipy-wheels/

**Comment by antocuni** [comment]
I tried to follow a bit the scripts but I admit I got lost and have no clue which libraries are used 😅

**Comment by Juanlu001** [comment]
I just went over `scipy-wheels` again and it's clear that they link against OpenBLAS. So, that's what we get when we install a NumPy or SciPy wheel in CPython.

**Comment by Juanlu001** [comment]
Apparently, there's some problem in building the Docker image.

**Comment by Juanlu001** [comment]
I mentioned this repository here: https://mail.python.org/pipermail/scipy-dev/2018-August/022999.html

**Comment by antocuni** [comment]
I am finally merging this. I tried to run things by hand and they seem to work, not sure why the travis build failed. Unfortunately, the changes will not be in effect until the next release of numpy/scipy, because at the moment the build system sees that the wheel is already present and skips it.
Moreover, it is not wise to upload a different wheel with the same name, it would confuse people

**Comment by rgommers** [comment]
Nice

> Moreover, it is not wise to upload a different wheel with the same name, it would confuse people

Indeed, that's not even possible anymore. You could do a `.post0` release, but those are a bit fishy imho, waiting for a next minor release seems better

**Comment by Juanlu001** [comment]
Thanks a lot @antocuni! When I received the notification I initially didn't realize that this PR was mine :sweat:

**Pull request merged**
